// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fix_ef_donet.DataContext;

#nullable disable

namespace fix_ef_donet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230110234235_AddAssetToDatabase")]
    partial class AddAssetToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("fix_ef_donet.DataContext.AssetEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AssetCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("asset_code");

                    b.Property<string>("AssetName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("asset_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("JumlahAsset")
                        .HasColumnType("int")
                        .HasColumnName("jumlah_asset");

                    b.Property<int>("PurchaseYear")
                        .HasColumnType("int")
                        .HasColumnName("purchase_year");

                    b.HasKey("Id");

                    b.ToTable("tbl_asset");
                });

            modelBuilder.Entity("fix_ef_donet.DataContext.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category_code");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.ToTable("tbl_category");
                });

            modelBuilder.Entity("fix_ef_donet.DataContext.HeroEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("HeroName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hero_name");

                    b.Property<int>("HeroPower")
                        .HasColumnType("int")
                        .HasColumnName("hero_power");

                    b.Property<string>("HeroRole")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("hero_role");

                    b.HasKey("Id");

                    b.ToTable("tbl_hero");
                });
#pragma warning restore 612, 618
        }
    }
}
